Algoritmo "P_1010"

Var

COD_PECA1, NUM_PECA1, COD_PECA2, NUM_PECA2: Inteiro
VALOR_PECA1, VALOR_PECA2, VALOR_FINAL: Real

Inicio

      Leia (COD_PECA1)

      Leia (NUM_PECA1)

      Leia (VALOR_PECA1)

      limpatela

      Leia (COD_PECA2)

      Leia (NUM_PECA2)

      Leia (VALOR_PECA2)

      VALOR_FINAL <- (NUM_PECA1 * VALOR_PECA1) + (NUM_PECA2 * VALOR_PECA2)

      Escreva ("VALOR A PAGAR: R$ ", VALOR_FINAL:1:2)

Fimalgoritmo